apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault-server
spec:
  values:
    injector:
      enabled: false

    server:
      affinity: "" # Use only for dev
      standalone:
        enabled: false
      ha:
        enabled: true
        replicas: 3
        raft:
          enabled: true
          setNodeId: true
      dataStorage:
        size: 100Mi
        storageClass: standard
      ingress:
        enabled: true
        ingressClassName: "nginx"
        pathType: Prefix
        activeService: true
        hosts:
          - host: vault.local.bytefusion.io
            paths: []
        extraPaths: []
        tls: []
    
    ui:
      enabled: true
