apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault-provider
spec:
  values:
    server:
      enabled: false
    injector:
      enabled: true
    csi:
      enabled: true
